[[redirects]]
  from = "/wp-admin/admin-ajax.php"
  to = "https://headlessmain.wpengine.com/builtbytophat/wp-admin/admin-ajax.php"
  status = 200
  force = true
  headers = {X-From = "Frontend"}

[[redirects]]
  from = "/wp-json/*"
  to = "https://headlessmain.wpengine.com/builtbytophat/wp-json/:splat"
  status = 200
  force = true
  headers = {X-From = "Frontend"}
